# Generated by Django 3.2.16 on 2022-12-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'yearOfRel', 'publisher')},
        ),
    ]
